sudo: required
languaje: node_js
node_js:
  - "9"
services:
  - docker
  - mongodb 
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
install:
  - npm install
script:
  - docker build -t vehicles .
deploy:
  provider: script
  skip_clean_up: true
  script:
    npm test;
  branch: main